// General types
export const SET_USER_INFO = "SET_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_SOCIAL_URLS = "UPDATE_SOCIAL_URLS";
export const UPDATE_USER_IMG = "UPDATE_USER_IMG";
export const UPDATE_USER_CV = "UPDATE_USER_CV";
export const UPDATE_USER_ABOUT = "UPDATE_USER_ABOUT";
export const UPDATE_USER_PHONE = "UPDATE_USER_PHONE";
export const UPDATE_USER_COUNTRY = "UPDATE_USER_COUNTRY";
export const UPDATE_USER_SKILLS = "UPDATE_USER_SKILLS";

export const DELETE_SOCIAL_URL = "DELETE_SOCIAL_URL";
export const DELETE_USER_IMG = "DELETE_USER_IMG";
export const DELETE_USER_CV = "DELETE_USER_CV";
export const DELETE_USER_PHONE = "DELETE_USER_PHONE";
export const DELETE_USER_SKILL = "DELETE_USER_SKILL";
export const DELETE_USER_ABOUT = "DELETE_USER_ABOUT";

// Dashboard
export const UPDATE_DASHBOARD_SIDEBAR = "UPDATE_DASHBOARD_SIDEBAR";

// Reset Password
export const REQUEST_PASSWORD_RESET = "REQUEST_PASSWORD_RESET";
export const PASSWORD_RESET_LOADING = "PASSWORD_RESET_LOADING";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";

// Jobs/Interns
// post
export const UPDATE_JOB_TITLE = "UPDATE_JOB_TITLE";
export const UPDATE_JOB_TYPE = "UPDATE_JOB_TYPE";
export const UPDATE_JOB_CATEGORY = "UPDATE_JOB_CATEGORY";
export const UPDATE_JOB_EDUCATION_LEVEL = "UPDATE_JOB_EDUCATION_LEVEL";
export const UPDATE_JOB_COMPANY_NAME = "UPDATE_JOB_COMPANY_NAME";
export const UPDATE_JOB_COMPANY_LOGO = "UPDATE_JOB_COMPANY_LOGO";
export const UPDATE_JOB_COMPANY_SIZE = "UPDATE_JOB_COMPANY_SIZE";
export const UPDATE_JOB_SALARY = "UPDATE_JOB_SALARY";
export const UPDATE_JOB_LOCATION = "UPDATE_JOB_LOCATION";
export const UPDATE_JOB_DESCRIPTION = "UPDATE_JOB_DESCRIPTION";
export const UPDATE_JOB_REQUIREMENT = "UPDATE_JOB_REQUIREMENT";
export const UPDATE_SELECTED_JOB_SKILLS_IDS = "UPDATE_SELECTED_JOB_SKILLS_IDS";
export const UPDATE_JOB_DEADLINE = "UPDATE_JOB_DEADLINE";
export const UPDATE_JOB_EXTERNAL_LINK = "UPDATE_JOB_EXTERNAL_LINK";
export const UPDATE_JOB_COMPANY_EMAIL = "UPDATE_JOB_COMPANY_EMAIL";
export const UPDATE_JOB_DURATION = "UPDATE_JOB_DURATION";
export const UPDATE_JOB_TIME = "UPDATE_JOB_TIME";
export const UPDATE_IS_INTER = "UPDATE_IS_INTER";

export const UPDATE_MISSING_INPUTS = "UPDATE_MISSING_INPUTS";
export const CLEAR_ALL_INPUTS = "CLEAR_ALL_INPUTS";

export const UPDATE_SELECT_JOB = "UPDATE_SELECT_JOB";

// apply
export const UPDATE_ALL_JOBS = "UPDATE_ALL_JOBS";
