// General types
export const SET_USER_INFO = "SET_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_SOCIAL_URLS = "UPDATE_SOCIAL_URLS";
export const UPDATE_USER_IMG = "UPDATE_USER_IMG";
export const UPDATE_USER_CV = "UPDATE_USER_CV";
export const UPDATE_USER_ABOUT = "UPDATE_USER_ABOUT";
export const UPDATE_USER_PHONE = "UPDATE_USER_PHONE";
export const UPDATE_USER_COUNTRY = "UPDATE_USER_COUNTRY";
export const UPDATE_USER_SKILLS = "UPDATE_USER_SKILLS";

export const DELETE_SOCIAL_URL = "DELETE_SOCIAL_URL";
export const DELETE_USER_IMG = "DELETE_USER_IMG";
export const DELETE_USER_CV = "DELETE_USER_CV";
export const DELETE_USER_PHONE = "DELETE_USER_PHONE";
export const DELETE_USER_SKILL = "DELETE_USER_SKILL";

// Dashboard
export const UPDATE_DASHBOARD_SIDEBAR = "UPDATE_DASHBOARD_SIDEBAR";

// Reset Password
export const REQUEST_PASSWORD_RESET = "REQUEST_PASSWORD_RESET";
export const UPDATE_PASSWORD_RESET_LOADING = "UPDATE_PASSWORD_RESET_LOADING";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILURE = "PASSWORD_RESET_FAILURE";
