export const SET_USER_INFO = "SET_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_SOCIAL_URLS = "UPDATE_SOCIAL_URLS";
export const UPDATE_USER_IMG = "UPDATE_USER_IMG";
export const UPDATE_USER_CV = "UPDATE_USER_CV";

export const DELETE_SOCIAL_URL = "DELETE_SOCIAL_URL";
